### ISSUE TITLE
Logcheck ignore sample

### ISSUE THREAD

**Issue by hooger** [matrix-hacks/matrix-puppet-facebook#50]
Hello guys,
Keep up the great work! I really hope I can abandon those blue, closed softwares both on desktop and on phone thanks to you. :)

**Description:**

I thought that it would be nice to have a default ignore file for logcheck, so regular restarts and events that usually happen but regarded as neutral not to bloat your root malibox.

Thank you in advance!

**Comment by thomas-profitt** [comment]
Other solutions to this may be:
- Have a configurable log_level for this
- Have different rooms for these status messages and important/unexpected messages like errors.

I agree that this is important.

To get it more exposure, and to get the issue in the right place (since this behavior is the same for other matrix-puppet-bridge bridges, e.g. slack, hangouts, etc.), would you please recreate this issue in https://github.com/matrix-hacks/matrix-puppet-bridge/issues and close this one?

**Comment by hooger** [comment]
I created https://github.com/matrix-hacks/matrix-puppet-bridge/issues/50, closing this one.
